name: Publish Release

on:
  push:
    branches: [master]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # registry: quay.io/oauth2-proxy
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build images
        run: |
          make REGISTRY=$REGISTRY REPOSITORY=$IMAGE_NAME docker

      - name: Push images
        run: |
          make REGISTRY=$REGISTRY REPOSITORY=$IMAGE_NAME docker-push
